### PR TITLE
Who's Rem Team submission

### PR DESCRIPTION
**Pull request by ChillFish8**

### CODE REVIEW

**Comment by kwzrd** [comment]
Hi @ChillFish8, your PR adds an `.idea` directory outside of your project folder. This is not allowed.

Due to the nature of this directory, deleting it should have no effect on your project. Could you please make an extra commit removing this directory, and push it? Please do not make any other changes in this commit.

We will then be able to merge your project. Thanks!

**Comment by ChillFish8** [comment]
I would be fine with deleting it however, How do i do that? 😅 As its hidden for me so i cant actually change it.

**Comment by ChillFish8** [comment]
Should be deleted now 👍

**Comment by kwzrd** [comment]
@ChillFish8 thanks, looks great!

**Pull request merged**
